# Site settings
title: Ad1tya's Blog
email: a@ad1.me
description: "Journal of a Nice Guy"
baseurl: ""
url: "http://www.ad1.me"
twitter_username: Ad1tyaS
github_username:  ad1tyas

# Build settings
markdown: kramdown
permalink: pretty
